// <auto-generated />
namespace Synonyms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class synonym_Creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(synonym_Creation));
        
        string IMigrationMetadata.Id
        {
            get { return "201603161604594_synonym_Creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
